### ISSUE TITLE
Unary counter bug

### ISSUE THREAD

**Issue by TheSecondComing123** [SantiagoBalbuena/NLRNIS#1]
```
>**">S*">N
"
>@*S*N+SS*@
``` 
should be the unary counter but it doesn't actually work. The error message in Git CMD is:

```python
Error in sys.excepthook:
Traceback (most recent call last):
  File "NLRNIS.py", line 39, in erroring
    print(end=errreason, file=sys.stderr)
TypeError: end must be None or a string, not Exception

Original exception was:
Traceback (most recent call last):
  File "NLRNIS.py", line 61, in <module>
    raise Exception("ERROR IN FILE", sys.argv[1], "VARIABLE NOT FOUND IN ITERATION", iteration)
Exception: ('ERROR IN FILE', 'file.txt', 'VARIABLE NOT FOUND IN ITERATION', 1)
```

**Comment by Fmbalbuena** [comment]
I will do this, but not now.
